declare interface IImageCarouselWebPartStrings {
  WebPartDescription: string;
  TemplateChecklistLabel: string;
  ViewFieldsChecklistLabel: string;
  ListIdChecklistLabel: string;
  WebUrlChecklistLabel: string;
  SiteUrlChecklistLabel: string;
  PlaceholderButtonLabel: string;
  PlaceholderIconText: string;
  SourcePageDescription: string;
  QueryPageDescription: string;
  DisplayPageDescription: string;
  SliderPropertiesDescription: string;
  SourceGroupName: string;
  QueryGroupName: string;
  DisplayGroupName: string;
  SliderProperties: string;
  SiteUrlFieldLabel: string;
  SiteUrlFieldPlaceholder: string;
  SiteUrlFieldLoadingLabel: string;
  SiteUrlFieldLoadingError: string;
  WebUrlFieldLabel: string;
  WebUrlFieldPlaceholder: string;
  WebUrlFieldLoadingLabel: string;
  WebUrlFieldLoadingError: string;
  ListTitleFieldLabel: string;
  ListTitleFieldPlaceholder: string;
  ListTitleFieldLoadingLabel: string;
  ListTitleFieldLoadingError: string;
  OrderByFieldLabel: string;
  OrderByFieldLoadingLabel: string;
  OrderByFieldLoadingError: string;
  ConfigureItemSelectorLabel: string;
  ClearItemSelectorLabel: string;
  ConfigureItemSelectorDescriptionLabel: string;
  ClearItemSelectorDescriptionLabel: string;
  LimitEnabledFieldLabel: string;
  ItemLimitPlaceholder: string;
  ErrorItemLimit: string;
  RecursiveEnabledFieldLabel: string;
  TemplateUrlFieldLabel: string;
  TemplateUrlPlaceholder: string;
  ExternalScriptsLabel: string;
  ExternalScriptsPlaceholder: string;
  ErrorTemplateExtension: string;
  ErrorTemplateResolve: string;
  ErrorWebAccessDenied: string;
  ErrorWebNotFound: string;
  ShowItemsAscending: string;
  ShowItemsDescending: string;
  DynamicallyGeneratedTemplate: string;
  IncompleteLabel: string;
  CompleteLabel: string;
  queryFilterPanelStrings: any;
  viewFieldsChecklistStrings: any;
  templateTextStrings: any;
  contentQueryStrings: any;

  AutoPlayFieldLabel:string;
  ShowThumbsFieldLabel:string;
  ShowIndicatosFieldLabel:string;
  ShowArrowsFieldLabel:string;
  StopOnHoverFieldLabel:string;
  PopUpFieldLabel:string;
  SpeedFieldLabel:string;
  InPixel:string;
  InPercentage:string;
  WidthFieldLabel:string;
  HeightFieldLabel:string;
  LegendFieldLabel: string;
  LegendFieldLoadingLabel: string;
  LegendFieldPlaceholder:string;
  NoItemToDisplay:string;
  NoItemToDisplayDespcription:string;
  CenterSlidePercentageFieldLabel:string;
}

declare module 'ImageCarouselWebPartStrings' {
  const strings: IImageCarouselWebPartStrings;
  export = strings;
}
